[package]
name = "destruction-studios/state-machine"
version = "1.1.5-beta-5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.3"