[package]
name = "destruction-studios/state-machine"
version = "1.1.7-beta-6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.3"
Trove = "sleitnick/trove@1.5.0"